import { and, desc, eq, lt, or } from "drizzle-orm";
import type { DrizzleD1Database } from "drizzle-orm/d1";
import * as schema from "../db/schema";
import { swaps } from "../db/schema";
import type {
  NewSwapRow,
  SwapDirection,
  SwapRow,
  SwapStatus,
} from "../db/schema";
import type { ErrorCode } from "../errors";
import { decodeCursor, encodeCursor } from "./cursor";

export type { SwapRow, SwapStatus } from "../db/schema";

/** Caller-supplied fields for a new pending swap; the repo fills id/status/createdAt and nulls. */
export type NewSwapInput = Omit<
  NewSwapRow,
  | "id"
  | "status"
  | "createdAt"
  | "txHash"
  | "actualAmountOut"
  | "errorCode"
  | "gasUsed"
  | "submittedAt"
  | "settledAt"
> & { direction: SwapDirection };

/** Persistence port for swap lifecycle rows: insert, state transitions, lookup, and paged listing. */
export interface TransactionsRepository {
  /** Insert a new row in `pending` state with a generated id; returns that id. */
  insertPending(row: NewSwapInput): Promise<string>;
  /** Transition a row to `submitted`, recording the broadcast tx hash and submit time. */
  markSubmitted(id: string, txHash: string): Promise<void>;
  /** Transition a row to `confirmed`, recording actual output, gas used, and settle time. */
  markConfirmed(
    id: string,
    r: { actualAmountOut: string; gasUsed: string },
  ): Promise<void>;
  /** Transition a row to `failed` with an error code; records `txHash` only when the swap reached the chain (omit it for pre-submit aborts, which clears it). */
  markFailed(
    id: string,
    errorCode: ErrorCode,
    opts?: { txHash?: string },
  ): Promise<void>;
  /** Return the current row for `id`, or `undefined` when none exists. */
  findById(id: string): Promise<SwapRow | undefined>;
  /**
   * Return a page of rows newest-first by `(createdAt, id)`. `limit` defaults to 20 and caps at
   * 100; `status` filters by lifecycle state; `cursor` resumes after a prior page. `nextCursor` is
   * null on the final page. Throws `AppError("invalid_input")` on a tampered or malformed cursor.
   */
  list(q: {
    limit?: number;
    cursor?: string;
    status?: SwapStatus;
  }): Promise<{ rows: SwapRow[]; nextCursor: string | null }>;
}

const DEFAULT_LIMIT = 20;
const MAX_LIMIT = 100;

/**
 * Build a {@link TransactionsRepository} over the given drizzle D1 client. See the interface for
 * each method's contract; this implementation stamps `submittedAt`/`settledAt` on transitions and,
 * in `list`, clamps `limit` to 1–100 and treats `cursor` as an opaque, tamper-checked token.
 */
export function createTransactionsRepository(
  db: DrizzleD1Database<typeof schema>,
): TransactionsRepository {
  return {
    async insertPending(row) {
      // `id` is generated by the schema's $defaultFn; read it back via returning().
      const [inserted] = await db
        .insert(swaps)
        .values({
          userId: row.userId,
          direction: row.direction,
          amountIn: row.amountIn,
          expectedAmountOut: row.expectedAmountOut ?? null,
          quotedAmountOut: row.quotedAmountOut,
          slippageTolerancePct: row.slippageTolerancePct,
          deadlineSeconds: row.deadlineSeconds,
          status: "pending",
          createdAt: Date.now(),
        })
        .returning({ id: swaps.id });
      return inserted.id;
    },

    async markSubmitted(id, txHash) {
      await db
        .update(swaps)
        .set({ status: "submitted", txHash, submittedAt: Date.now() })
        .where(eq(swaps.id, id));
    },

    async markConfirmed(id, r) {
      await db
        .update(swaps)
        .set({
          status: "confirmed",
          actualAmountOut: r.actualAmountOut,
          gasUsed: r.gasUsed,
          settledAt: Date.now(),
        })
        .where(eq(swaps.id, id));
    },

    async markFailed(id, errorCode, opts) {
      await db
        .update(swaps)
        .set({
          status: "failed",
          errorCode,
          txHash: opts?.txHash ?? null,
          settledAt: Date.now(),
        })
        .where(eq(swaps.id, id));
    },

    async findById(id) {
      return db.query.swaps.findFirst({ where: eq(swaps.id, id) });
    },

    async list(q) {
      const limit = Math.min(Math.max(q.limit ?? DEFAULT_LIMIT, 1), MAX_LIMIT);

      const statusFilter = q.status ? eq(swaps.status, q.status) : undefined;

      let cursorFilter;
      if (q.cursor !== undefined) {
        const c = decodeCursor(q.cursor);
        cursorFilter = or(
          lt(swaps.createdAt, c.createdAt),
          and(eq(swaps.createdAt, c.createdAt), lt(swaps.id, c.id)),
        );
      }

      const where = and(statusFilter, cursorFilter);

      const found = await db.query.swaps.findMany({
        where,
        orderBy: [desc(swaps.createdAt), desc(swaps.id)],
        limit: limit + 1,
      });

      const hasMore = found.length > limit;
      const rows = hasMore ? found.slice(0, limit) : found;
      const last = rows[rows.length - 1];
      const nextCursor =
        hasMore && last
          ? encodeCursor({ createdAt: last.createdAt, id: last.id })
          : null;

      return { rows, nextCursor };
    },
  };
}
